let arr= [10, true, 25, "hello", "world", 28, false, 35, 1.3, 88];
console.log(arr);
console.log(arr [0]);
console.log(arr[1]);
console.log(arr[2]);
console.log(arr[3]);
console.log(arr[4]);
console.log(arr[5]);
console.log(arr[6]);
console.log(arr[7]);
console.log(arr[8]);
console.log(arr[9]);
